### ISSUE TITLE
Model Size Inquiry 

### ISSUE THREAD

**Issue by HamDan1999** [fdbtrs/QuantFace#1]
Firstly, I really admire all your works (PocketNet, QuantFace, MixFaceNets).

I have a question, how did you calculate the model sizes? both real models and quantized models?

Thanks!

**Comment by fdbtrs** [comment]
model size equals to original model size divided by the bit reduction. If you need to get the actual size on the hard disk, you need to convert the model to quantized model.

**Comment by HamDan1999** [comment]
Noted with thanks!
